
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerServiceWebserviceImplementationService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/CustomerManagementServerApplication/CustomerManagementWebService?wsdl")
public class CustomerServiceWebserviceImplementationService
    extends Service
{

    private final static URL CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://service/", "CustomerServiceWebserviceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CustomerManagementServerApplication/CustomerManagementWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public CustomerServiceWebserviceImplementationService() {
        super(__getWsdlLocation(), CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public CustomerServiceWebserviceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public CustomerServiceWebserviceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public CustomerServiceWebserviceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public CustomerServiceWebserviceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerServiceWebserviceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerManagementWebService
     */
    @WebEndpoint(name = "CustomerManagementWebServicePort")
    public CustomerManagementWebService getCustomerManagementWebServicePort() {
        return super.getPort(new QName("http://service/", "CustomerManagementWebServicePort"), CustomerManagementWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerManagementWebService
     */
    @WebEndpoint(name = "CustomerManagementWebServicePort")
    public CustomerManagementWebService getCustomerManagementWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "CustomerManagementWebServicePort"), CustomerManagementWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return CUSTOMERSERVICEWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
