
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerManagementWebService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerManagementWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateAccountManager", targetNamespace = "http://service/", className = "service.UpdateAccountManager")
    @ResponseWrapper(localName = "updateAccountManagerResponse", targetNamespace = "http://service/", className = "service.UpdateAccountManagerResponse")
    public void updateAccountManager(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateAddress", targetNamespace = "http://service/", className = "service.UpdateAddress")
    @ResponseWrapper(localName = "updateAddressResponse", targetNamespace = "http://service/", className = "service.UpdateAddressResponse")
    public void updateAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCustomers", targetNamespace = "http://service/", className = "service.GetAllCustomers")
    @ResponseWrapper(localName = "getAllCustomersResponse", targetNamespace = "http://service/", className = "service.GetAllCustomersResponse")
    public List<Customer> getAllCustomers();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateEmail", targetNamespace = "http://service/", className = "service.UpdateEmail")
    @ResponseWrapper(localName = "updateEmailResponse", targetNamespace = "http://service/", className = "service.UpdateEmailResponse")
    public void updateEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "identifyCustomer", targetNamespace = "http://service/", className = "service.IdentifyCustomer")
    @ResponseWrapper(localName = "identifyCustomerResponse", targetNamespace = "http://service/", className = "service.IdentifyCustomerResponse")
    public Customer identifyCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateCustomergroup", targetNamespace = "http://service/", className = "service.UpdateCustomergroup")
    @ResponseWrapper(localName = "updateCustomergroupResponse", targetNamespace = "http://service/", className = "service.UpdateCustomergroupResponse")
    public void updateCustomergroup(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchBySurname", targetNamespace = "http://service/", className = "service.SearchBySurname")
    @ResponseWrapper(localName = "searchBySurnameResponse", targetNamespace = "http://service/", className = "service.SearchBySurnameResponse")
    public List<Customer> searchBySurname(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updatePhoneNr", targetNamespace = "http://service/", className = "service.UpdatePhoneNr")
    @ResponseWrapper(localName = "updatePhoneNrResponse", targetNamespace = "http://service/", className = "service.UpdatePhoneNrResponse")
    public void updatePhoneNr(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerCustomer", targetNamespace = "http://service/", className = "service.RegisterCustomer")
    @ResponseWrapper(localName = "registerCustomerResponse", targetNamespace = "http://service/", className = "service.RegisterCustomerResponse")
    public void registerCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeCustomer", targetNamespace = "http://service/", className = "service.RemoveCustomer")
    @ResponseWrapper(localName = "removeCustomerResponse", targetNamespace = "http://service/", className = "service.RemoveCustomerResponse")
    public void removeCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://service/", className = "service.UpdateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://service/", className = "service.UpdateCustomerResponse")
    public void updateCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

}
